export const COMMENTS_REJECT = "COMMENTS_REJECT";
export const COMMENTS_RESOLVE = "COMMENTS_RESOLVE";
export const COMMENTS_DELETE_REJECT = "COMMENTS_DELETE_REJECT";
export const COMMENTS_DELETE_RESOLVE = "COMMENTS_DELETE_RESOLVE";
