export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAIL = "GET_POSTS_FAIL";

export const ADD_POST_REQUEST = "ADD_POST_REQUEST";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAIL = "ADD_POST_FAIL";

export const PATCH_POST_REQUEST = "PATCH_POST_REQUEST";
export const PATCH_POST_SUCCESS = "PATCH_POST_SUCCESS";
export const PATCH_POST_FAIL = "PATCH_POST_FAIL";
